language: csharp
solution: project.sln

os: linux
dist: xenial
sudo: enabled

mono: none
dotnet: 2.2

before_script:
  - cp ./src/appsettings.private.example.json ./src/appsettings.private.json

script:
  - dotnet restore --verbosity q
  - dotnet build --configuration Debug --no-restore --verbosity q
  - dotnet build --configuration Release --no-restore --verbosity q
  - dotnet test --filter FullyQualifiedName~"Walpy.VacancyApp.Test.Api.Vacancy.GetAllTest" --configuration Release --no-restore --no-build --verbosity n
  - dotnet test --filter FullyQualifiedName~"Walpy.VacancyApp.Test.Api.Vacancy.GetTest" --configuration Release --no-restore --no-build --verbosity n
  - dotnet test --filter FullyQualifiedName~"Walpy.VacancyApp.Test.Api.Vacancy.AddTest" --configuration Release --no-restore --no-build --verbosity n
  - dotnet test --filter FullyQualifiedName~"Walpy.VacancyApp.Test.Api.Vacancy.DeleteTest" --configuration Release --no-restore --no-build --verbosity n
  - dotnet test --filter FullyQualifiedName~"Walpy.VacancyApp.Test.Api.Vacancy.UpdateTest.Valid200Title" --configuration Release --no-restore --no-build --verbosity n
  - dotnet test --filter FullyQualifiedName~"Walpy.VacancyApp.Test.Api.Vacancy.UpdateTest.Valid200Description" --configuration Release --no-restore --no-build --verbosity n
  - dotnet test --filter FullyQualifiedName~"Walpy.VacancyApp.Test.Api.Vacancy.UpdateTest.Valid200Salary" --configuration Release --no-restore --no-build --verbosity n
  - dotnet test --filter FullyQualifiedName~"Walpy.VacancyApp.Test.Api.Vacancy.UpdateTest.Valid200ContactPhone" --configuration Release --no-restore --no-build --verbosity n
  - dotnet test --filter FullyQualifiedName~"Walpy.VacancyApp.Test.Api.Vacancy.UpdateTest.Valid200ContactPerson" --configuration Release --no-restore --no-build --verbosity n

after_failure:
  - cat ./out/log/*.trx

notifications:
  email:
    template:
      - "%{author}/%{repository_slug}.%{branch} -> %{commit_message}"
      - "%{result} [%{duration}] -> %{message}"
      - "%{build_url} | %{compare_url}"
    recipients:
      - walpy.notice@gmail.com
    on_success: change
    on_failure: change