language: csharp
solution: project.sln

matrix:
  include:

    - os: linux
      dist: xenial
      sudo: enabled
      mono: none
      dotnet: 2.2
      after_failure: cat ./out/log/*.trx

    #? see https://github.com/vulmy/server/blob/master/.travis.yml#L33
    #?  about configuring on travis wondows;
    - os: windows
      language: shell
      install:
        - choco install mysql
        - choco install dotnetcore-sdk
      after_failure:
        - cd out
        - cd log
        - powershell -c Get-Content *.trx

script:
  - dotnet restore --verbosity q
  - dotnet build --configuration Debug --no-restore --verbosity q
  - dotnet test --configuration Debug --no-restore --no-build --verbosity n

notifications:
  email:
    template:
      - "%{author}/%{repository_slug}.%{branch} -> %{commit_message}"
      - "%{result} [%{duration}] -> %{message}"
      - "%{build_url} | %{compare_url}"
    recipients:
      - walpy.notice@gmail.com
    on_success: change
    on_failure: change