language: csharp
solution: project.sln

matrix:
  include:

    - os: linux
      dist: xenial
      sudo: enabled
      mono: none
      dotnet: 2.2
      before_script:
        - cp ./src/appsettings.private.example.json ./src/appsettings.private.json
      after_failure: cat ./out/log/*.trx

    #? see https://github.com/vulmy/server/blob/master/.travis.yml#L33
    #?  about configuring on travis wondows;
    - os: windows
      language: shell
      install:
        - choco install mysql
        - choco install dotnetcore-sdk
      before_script:
        - cd src
        - copy appsettings.private.example.json appsettings.private.json
        - cd ..
      after_failure:
        - cd out
        - cd log
        - powershell -c Get-Content *.trx

script:
  - dotnet restore --verbosity q
  - dotnet build --configuration Debug --no-restore --verbosity q
  - dotnet build --configuration Release --no-restore --verbosity q
  - dotnet test --filter FullyQualifiedName~"App.Server.Test.Api.Vacancy.GetAllTest" --configuration Release --no-restore --no-build --verbosity n
  - dotnet test --filter FullyQualifiedName~"App.Server.Test.Api.Vacancy.GetTest" --configuration Release --no-restore --no-build --verbosity n
  - dotnet test --filter FullyQualifiedName~"App.Server.Test.Api.Vacancy.AddTest" --configuration Release --no-restore --no-build --verbosity n
  - dotnet test --filter FullyQualifiedName~"App.Server.Test.Api.Vacancy.DeleteTest" --configuration Release --no-restore --no-build --verbosity n
  - dotnet test --filter FullyQualifiedName~"App.Server.Test.Api.Vacancy.UpdateTest.Valid200Title" --configuration Release --no-restore --no-build --verbosity n
  - dotnet test --filter FullyQualifiedName~"App.Server.Test.Api.Vacancy.UpdateTest.Valid200Description" --configuration Release --no-restore --no-build --verbosity n
  - dotnet test --filter FullyQualifiedName~"App.Server.Test.Api.Vacancy.UpdateTest.Valid200Salary" --configuration Release --no-restore --no-build --verbosity n
  - dotnet test --filter FullyQualifiedName~"App.Server.Test.Api.Vacancy.UpdateTest.Valid200ContactPhone" --configuration Release --no-restore --no-build --verbosity n
  - dotnet test --filter FullyQualifiedName~"App.Server.Test.Api.Vacancy.UpdateTest.Valid200ContactPerson" --configuration Release --no-restore --no-build --verbosity n

notifications:
  email:
    template:
      - "%{author}/%{repository_slug}.%{branch} -> %{commit_message}"
      - "%{result} [%{duration}] -> %{message}"
      - "%{build_url} | %{compare_url}"
    recipients:
      - walpy.notice@gmail.com
    on_success: change
    on_failure: change