language: csharp
solution: project.sln

os: linux
dist: xenial
sudo: enabled

mono: none
dotnet: 2.2

before_script:
  - cp ./src/all/appsettings.private.example.json ./src/all/appsettings.private.json

script:
  - dotnet restore --verbosity q
  - dotnet build --configuration Debug --no-restore --verbosity q
  - dotnet build --configuration Release --no-restore --verbosity q
  - dotnet test

after_failure:
  - cat ./out/log/*.trx

notifications:
  email:
    template:
      - "%{author}/%{repository_slug}.%{branch} -> %{commit_message}"
      - "%{result} [%{duration}] -> %{message}"
      - "%{build_url} | %{compare_url}"
    recipients:
      - walpy.notice@gmail.com
    on_success: change
    on_failure: change