version: '{build}'
image: Visual Studio 2019 Preview

environment:
  SHORT_TEST: true

init:
  - cmd: dotnet --version
build_script:
  - cmd: dotnet restore --verbosity q
  - cmd: dotnet build -c Debug --no-restore --verbosity q
  - cmd: dotnet build -c Release --no-restore --verbosity q
test_script:
  - cmd: dotnet test --configuration Release --no-restore --no-build --verbosity n