version: '{build}'
image: Visual Studio 2019 Preview

init:
  - cmd: dotnet --version
before_build:
  - ps: Copy-Item src\appsettings.private.example.json src\appsettings.private.json
build_script:
  - cmd: dotnet restore --verbosity q
  - cmd: dotnet build -c Debug --no-restore --verbosity q
  - cmd: dotnet build -c Release --no-restore --verbosity q
test_script:
  - cmd: dotnet test -c Release --no-restore --no-build --verbosity diag