version: "3.0"

services:
  database:
    image: mysql:5.7.25
    enviroment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: vacancyAppDb
      MYSQL_USER: vacancyApp
      MYSQL_PASSWORD: DYAdewDbfTXrKKfS
    volumes:
      - dbdata: /var/lib/mysql
      - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
    restart: always

  vacancyapp:
    depends_on:
      - database
    image: walpy/vacancyapp
    ports:
      - "5099:5000"
    build:
      context: .
    restart: always

volumes:
  dbdata: